substitutions:
  _VITE_GEMINI_API_KEY: 'your api key'
  _VITE_GOOGLE_MAPS_API_KEY: 'your api key'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_GEMINI_API_KEY=$_VITE_GEMINI_API_KEY'
      - '--build-arg'
      - 'VITE_GOOGLE_MAPS_API_KEY=$_VITE_GOOGLE_MAPS_API_KEY'
      - '-t'
      - 'gcr.io/beyondthehorizon-495923/beyond-the-horizon:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/beyondthehorizon-495923/beyond-the-horizon:latest'
images:
  - 'gcr.io/beyondthehorizon-495923/beyond-the-horizon:latest'
